### ISSUE TITLE
Trouble Implementing a New Component

### ISSUE THREAD

**Issue by dkieffer** [dkieffer/timeblob#3]
Line 36 in index template `<list-view-nav />` I'm trying to include a new component here, but I'm doing something wrong. CSS only will display this nav bar for handhelds. cc @ericschultz

**Comment by wwahammy** [comment]
I'm looking through it now and I'm not sure I understand what's going on. We should talk through what you're trying to do.

**Comment by dkieffer** [comment]
Typescript!
